### ISSUE TITLE
Cannot click on the app after switching windows

### ISSUE THREAD

**Issue by tommytran732** [flathub/io.github.hmlendea.geforcenow-electron#1]
I am having a quite weird issue with the geforce app. If I am playing a game in full screen and I switch to another workspace on GNOME, or if I minimize all applications and reopen the app, it will stop registering my mouse. I can move my mouse on the screen but I cannot click on anything in Geforce Now.

If I open another app on top of Geforce Now, then minimize that app, the mouse works again. 

I am using Fedora Silverblue 34 (tho this issue can be replicated on Fedora Workstation 34 as well).

**Comment by hmlendea** [comment]
Hi @tommytran732 is this still going on?

**Comment by tommytran732** [comment]
> Hi @tommytran732 is this still going on?

Hi,

This is fixed. Thank you.
