### ISSUE TITLE
could you add copy / paste support?

### ISSUE THREAD

**Issue by RemyFV** [flathub/io.github.hmlendea.geforcenow-electron#22]
this is the main issue I have with GFN pretty much everywhere, and on the steam deck typing passwords is just horrible with keyboard language conflicts on top...

copy / paste support in this would be a lifesaver.

**Comment by hmlendea** [comment]
Hi,

I completely agree with this... but I'm not able to do it. GFN is simply too "tight" and there's no room to implement improvements reliably.

I would love if there was copy-paste support, but the only way I can see it happen is if GFN itself adds that feature.

**Comment by RemyFV** [comment]
I was thinking there would probably be a way to have this kind of autohotkey script through the Electron layer:

`SetKeyDelay, 0
^v::
send %clipboard%`

it takes clipboard content and sends independent key inputs to "type" the text in whatever is focused.

**Comment by zocker-160** [comment]
the latest version of GFN (2.0.41) added support for CTRL + V and I can confirm it is working

**Comment by RemyFV** [comment]
great!
